cms/urls.py
from django.urls import path, re_path

from cms.views import IndexView
from cms.views import ProductsView
from cms.views import ProductsAddView
from cms.views import ProductsEditView
from cms.views import ProductsCopyView
from cms.views import TreeView, Attributes, ModalAttribute
from cms.views import TreeView, CatalogsModals
from cms.views import Tags, ModalTags, TaggingProducts

urlpatterns = [
    path('', IndexView.as_view(), name='cms.index'),

    path('products/', ProductsView.as_view(), name='cms.product.list'),
    path('products/add', ProductsAddView.as_view(), name='cms.product.add'),
    path('products/edit/<int:product_id>', ProductsEditView.as_view(), name='cms.product.edit'),
    path('products/copy/<int:product_id>', ProductsCopyView.as_view(), name='cms.product.copy'),

    path('catalog/<int:cat_id>', TreeView.as_view(), name='cms.tree'),
    path('catalog/', TreeView.as_view(), name='cms.tree'),
    path('catalog/m/<str:type_modal>', CatalogsModals.as_view(), name='cms.tree.modal'),

    re_path(r'^attributes/((?P<attr_id>\w+)/)?$', Attributes.as_view(), name='cms.attributes'),
    re_path(r'^modals/attributes/((?P<attr_id>\w+)/)?$', ModalAttribute.as_view(), name='cms.attributes.modal'),

    re_path(r'^tags/((?P<tag_id>\w+)/)?$', Tags.as_view(), name='cms.tags'),
    re_path(r'^modals/tags/((?P<tag_id>\w+)/)?$', ModalTags.as_view(), name='cms.tags.modal'),

    path('products/tagging/', TaggingProducts.as_view(), name='cms.product.tagging')
]

cms/models.py
from django.db import models

# Create your models here.

shop/models/catalog.py
import uuid

from django.db import models
from imagekit.models import ImageSpecField
from mptt.models import MPTTModel, TreeForeignKey
from pilkit.processors import ResizeToFit, ResizeToCover, ResizeToFill


def upload_to(instance, filename):
    filename = str(uuid.uuid1()) + "." + filename.split('.', 1)[-1]
    return 'catalog/{}/{}'.format(instance.catalog.pk, filename)


class Catalog(MPTTModel):
    title = models.CharField(max_length=300, db_index=True)
    code = models.SlugField(db_index=True)
    has_sub_cat = models.BooleanField(default=False, blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True, on_delete=models.SET_NULL)
    is_delete = models.BooleanField(default=False, blank=True)
    sort_position = models.SmallIntegerField(default=0, blank=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        if self.parent:
            return "{} - {}".format(self.parent.title, self.title)
        return self.title

    class Meta:
        verbose_name = 'Товарная Категория'
        verbose_name_plural = 'Товарные Категории'
        ordering = ['sort_position']


class CatalogTag(models.Model):
    catalog = models.ForeignKey(Catalog, on_delete=models.SET_NULL, db_index=True, null=True)
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL, db_index=True, null=True)


class CatalogImage(models.Model):
    catalog = models.ForeignKey(Catalog, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField('date created', auto_now_add=True)
    link = models.ImageField(upload_to=upload_to)
    full = ImageSpecField(source='link',
                          processors=[],
                          format='PNG',
                          options={'quality': 60})
    thumbnail = ImageSpecField(source='link',
                               processors=[ResizeToFill(width=370, height=370)],
                               format='PNG',
                               options={'quality': 60})

    editor = ImageSpecField(source='link',
                            processors=[ResizeToFill(width=100, height=100)],
                            format='PNG',
                            options={'quality': 60})

    is_delete = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.catalog.title

    class Meta:
        verbose_name = 'Изображение каталога'
        verbose_name_plural = 'Изображения разделов каталога'

cms/forms/form_attribute.py
from django.forms import ModelForm
from shop.models import AttributeForProduct


class FormAttribute(ModelForm):
    class Meta:
        model = AttributeForProduct
        fields = ['title', 'code', 'cast_type']

cms/forms/form_catalog.py
from django.forms import ModelForm
from shop.models import Catalog


class FormCatalog(ModelForm):
    class Meta:
        model = Catalog
        fields = ['title', 'parent', 'code']

cms/forms/form_product.py
from django.forms import ModelForm
from shop.models import Product


class FormProduct(ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price']

cms/forms/form_tag.py
from django.forms import ModelForm
from shop.models import Tag


class FormTag(ModelForm):
    class Meta:
        model = Tag
        fields = ['title', 'code']

cms/views.py
from django.shortcuts import render

# Create your views here.

cms/views/index.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View


class IndexView(View):
    def get(self, request):
        return render(request=request, template_name='cms/index.html', context={"is_breadcrumbs": False, "landing": True})
        # return HttpResponse("Hello, world. You're at the index.")

shop/views/catalogView.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from shop.adapters import CatalogAdapter


class CatalogView(View):
    def get(self, request):

        breadcrumbs = [
            {
                "uri": "/",
                "title": "Главная"
            },
            {
                "uri": "#",
                "title": "Каталог"
            }
        ]

        try:
            catalog_nodes = CatalogAdapter.get_catalog_nodes()
        except:
            catalog_nodes = []
        return render(
            request=request,
            template_name='catalog.html',
            context={"is_breadcrumbs": True, "breadcrumbs": breadcrumbs, "nodes": catalog_nodes}
        )
        # return HttpResponse("Hello, world. You're at the CatalogView.")

templates/cms/catalog/modal-add-sub.html
<h4>Изменить {{ element.title }}</h4>
<form class="form-horizontal" role="form" id="add-subcat" data-method="POST" data-action="/cms/catalog/">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="titleField"> Название </label>
        <div class="col-md-8">
            <input type="text" id="titleField" name="title" placeholder="Название" class="col-md-12" value="{{ element.title }}"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="codeField"> Сомвольный код </label>
        <div class="col-md-8">
            <input type="text" id="codeField" name="code" placeholder="Символьный код" class="col-md-12" value="{{ element.code }}"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="parentSelect">Родительская категория</label>
        <div class="col-md-8">
            <select readonly class="form-control col-md-12" id="parentSelect" name="parent">
                <option value="{{ parent.pk }}">{{ parent.title }}</option>
            </select>
        </div>
    </div>
    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="button" onclick="submitForm(this)" data-form="add-subcat">
                <i class="ace-icon fa fa-check bigger-110"></i>
                Сохранить
            </button>
        </div>
    </div>

</form>

templates/cms/catalog/modal-add.html
<h4>Добавить</h4>
<form class="form-horizontal" role="form" id="add-root" data-method="POST"
      data-action="/cms/catalog/">
    {% csrf_token %}

    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="titleField"> Название </label>
        <div class="col-md-8">
            <input type="text" id="titleField" name="title" placeholder="Название" class="col-md-12"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="codeField"> Сомвольный код </label>
        <div class="col-md-8">
            <input type="text" id="codeField" name="code" placeholder="Символьный код" class="col-md-12"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-12">
            <input type="file" id="image" name="image"/>
        </div>
    </div>
    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="button" onclick="submitForm(this)" data-form="add-root">
                <i class="ace-icon fa fa-check bigger-110"></i>
                Сохранить
            </button>
        </div>
    </div>
</form>

templates/cms/catalog/modal-edit-child.html
<h4>Изменить {{ element.title }}</h4>
<form class="form-horizontal" role="form" id="edit-subcat" data-method="POST" data-action="/cms/catalog/{{ element.pk }}">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="titleField"> Название </label>
        <div class="col-md-8">
            <input type="text" id="titleField" name="title" placeholder="Название" class="col-md-12" value="{{ element.title }}"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="codeField"> Сомвольный код </label>
        <div class="col-md-8">
            <input type="text" id="codeField" name="code" placeholder="Символьный код" class="col-md-12" value="{{ element.code }}"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="parentSelect">Родительская категория</label>
        <div class="col-md-8">
            <select class="form-control col-md-12" id="parentSelect" name="parent">
                <option value="" readonly disabled>------</option>
                {% for root in parents %}
                     <option value="{{ root.pk }}">{{ root.title }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="button" onclick="submitForm(this)" data-form="edit-subcat">
                <i class="ace-icon fa fa-check bigger-110"></i>
                Сохранить
            </button>
        </div>
    </div>

</form>

templates/cms/catalog/modal-edit-root.html
<h4>Изменить {{ element.title }}</h4>
<form class="form-horizontal" role="form" id="edit-cat" data-method="POST"
      data-action="/cms/catalog/{{ element.pk }}">
    {% csrf_token %}

    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="titleField"> Название </label>
        <div class="col-md-8">
            <input type="text" id="titleField" name="title" placeholder="Название" class="col-md-12"
                   value="{{ element.title }}"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label no-padding-right" for="codeField"> Сомвольный код </label>
        <div class="col-md-8">
            <input type="text" id="codeField" name="code" placeholder="Символьный код" class="col-md-12"
                   value="{{ element.code }}"/>
        </div>
    </div>
    <div class="form-group">
        <img src="{{ element.catalogimage_set.all.0.thumbnail.url }}"/>
    </div>
    <div class="form-group">
        <div class="col-xs-12">
            <input type="file" id="image" name="image"/>
        </div>
    </div>
    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="button" onclick="submitForm(this)" data-form="edit-cat">
                <i class="ace-icon fa fa-check bigger-110"></i>
                Сохранить
            </button>
        </div>
    </div>
</form>

templates/cms/catalog/tree.html
{% extends 'cms/base.html' %}
{% load static from staticfiles %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter green">Глобальные действия</h3>
            <p></p>
            <a href="#" class="btn btn-success btn-app radius-4 add-root">
                <i class="ace-icon fa fa-plus bigger-230"></i>
                Добавить
            </a>
        </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
        <div class="dd dd-draghandle" id="nestable">
            <ol class="dd-list">
                {% for root in tree %}
                    <li class="dd-item dd2-item" data-id="{{ root.pk }}">
                        <div class="dd-handle dd2-handle">
                            <i class="normal-icon ace-icon fa fa-arrows bigger-130"></i>
                            <i class="drag-icon ace-icon blue fa fa-arrows bigger-125"></i>
                        </div>
                        <div class="dd2-content">
                            {{ root.title }}
                            <div class="pull-right action-buttons">
                                <a class="blue edit-cat-btn" href="#" data-id="{{ root.pk }}">
                                    <i class="ace-icon fa fa-pencil bigger-130"></i>
                                </a>
                                <a class="green add-subcat-btn" href="#" data-id="{{ root.pk }}">
                                    <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                                </a>
                            </div>
                        </div>
                        {% if root.child %}
                            <ol class="dd-list">
                                {% for child in root.child %}
                                    <li class="dd-item dd2-item" data-id="{{ child.pk }}">
                                        <div class="dd-handle dd2-handle">
                                            <i class="normal-icon ace-icon fa fa-arrows bigger-130"></i>
                                            <i class="drag-icon ace-icon blue fa fa-arrows bigger-125"></i>
                                        </div>
                                        <div class="dd2-content">
                                            {{ child.title }}
                                            <div class="pull-right action-buttons">
                                                <a class="blue edit-cat-btn" href="#" data-id="{{ child.pk }}">
                                                    <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ol>
                        {% endif %}
                    </li>
                {% endfor %}
            </ol>
        </div>
    </div>
    <!-- inline scripts related to this page -->
{% endblock %}
{% block exta_files %}
    <script type="text/javascript" src="{% static "cms/assets/js/jquery.nestable.min.js" %}"></script>
    <script type="text/javascript" src="{% static "cms/js/catalog.js" %}"></script>
    <script type="text/javascript" src="{% static "cms/assets/js/bootbox.js" %}"></script>
    <script type="text/javascript" src="{% static "cms/assets/js/ace-elements.min.js" %}"></script>
{% endblock %}