cms/urls.py
from django.urls import path, re_path

from cms.views import IndexView
from cms.views import ProductsView
from cms.views import ProductsAddView
from cms.views import ProductsEditView
from cms.views import ProductsCopyView
from cms.views import TreeView, Attributes, ModalAttribute
from cms.views import TreeView, CatalogsModals
from cms.views import Tags, ModalTags, TaggingProducts

urlpatterns = [
    path('', IndexView.as_view(), name='cms.index'),

    path('products/', ProductsView.as_view(), name='cms.product.list'),
    path('products/add', ProductsAddView.as_view(), name='cms.product.add'),
    path('products/edit/<int:product_id>', ProductsEditView.as_view(), name='cms.product.edit'),
    path('products/copy/<int:product_id>', ProductsCopyView.as_view(), name='cms.product.copy'),

    path('catalog/<int:cat_id>', TreeView.as_view(), name='cms.tree'),
    path('catalog/', TreeView.as_view(), name='cms.tree'),
    path('catalog/m/<str:type_modal>', CatalogsModals.as_view(), name='cms.tree.modal'),

    re_path(r'^attributes/((?P<attr_id>\w+)/)?$', Attributes.as_view(), name='cms.attributes'),
    re_path(r'^modals/attributes/((?P<attr_id>\w+)/)?$', ModalAttribute.as_view(), name='cms.attributes.modal'),

    re_path(r'^tags/((?P<tag_id>\w+)/)?$', Tags.as_view(), name='cms.tags'),
    re_path(r'^modals/tags/((?P<tag_id>\w+)/)?$', ModalTags.as_view(), name='cms.tags.modal'),

    path('products/tagging/', TaggingProducts.as_view(), name='cms.product.tagging')
]

cms/models.py
from django.db import models

# Create your models here.

shop/models/product.py
from django.db import models
import uuid
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, SmartResize, ResizeToFit, ResizeToCover


def upload_to(instance, filename):
    filename = str(uuid.uuid1()) + "." + filename.split('.', 1)[-1]
    return 'products/{}/{}'.format(instance.product.pk, filename)


class ProductClass(models.Model):
    title = models.CharField(max_length=300, db_index=True)
    has_variants = models.BooleanField(default=False, blank=True)
    is_delete = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид товара'
        verbose_name_plural = 'Виды товаров'


class ProductBrand(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    code = models.CharField(max_length=200, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Товарный бренд'
        verbose_name_plural = 'Товарные бренды'


class Product(models.Model):
    product_class = models.ForeignKey(ProductClass, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=300, db_index=True)
    description = models.TextField()
    is_featured = models.BooleanField(default=True, blank=True)
    price = models.FloatField(default=0.00)
    created_at = models.DateTimeField(auto_now_add=True)
    is_delete = models.BooleanField(default=False, blank=True)
    brand = models.ForeignKey(ProductBrand, on_delete=models.DO_NOTHING, blank=True, null=True)
    code = models.CharField(max_length=255)

    def __str__(self):
        if self.product_class.has_variants:
            return "#{} - {}, цена - {}, ВАРИАНТНЫЙ".format(self.pk, self.title, self.price)
        return "#{} - {}, цена - {}".format(self.pk, self.title, self.price)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, db_index=True)
    override_price = models.DecimalField(blank=True, max_digits=12, decimal_places=2, default=0.00)
    sku = models.CharField(max_length=300, db_index=True)
    is_delete = models.BooleanField(default=False, blank=True)
    is_featured = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return "#{}#{} - {} - {} , цена {}".format(self.product.pk, self.pk, self.product.title, self.sku, self.override_price)

    class Meta:
        verbose_name = 'Разновидность товара'
        verbose_name_plural = 'Разновидность товара'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, db_index=True)
    created_at = models.DateTimeField('date created', auto_now_add=True)
    link = models.ImageField(upload_to=upload_to)
    full = ImageSpecField(source='link',
                          processors=[],
                          format='PNG',
                          options={'quality': 60})
    thumbnail = ImageSpecField(source='link',
                               processors=[ResizeToCover(width=370, height=370)],
                               format='PNG',
                               options={'quality': 60})

    x600 = ImageSpecField(source='link',
                          processors=[ResizeToCover(width=600, height=600)],
                          format='PNG',
                          options={'quality': 60})

    paging = ImageSpecField(source='link',
                            processors=[ResizeToFit(147, 143)],
                            format='PNG',
                            options={'quality': 60})
    is_delete = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return "{} - {}".format(self.product.pk, self.product.title)

    class Meta:
        verbose_name = 'Изображение товара'
        verbose_name_plural = 'Изображения товаров'


class VariantImage(models.Model):
    product = models.ForeignKey(ProductVariant, on_delete=models.DO_NOTHING, db_index=True)
    created_at = models.DateTimeField('date created', auto_now_add=True)
    link = models.ImageField(upload_to=upload_to)
    full = ImageSpecField(source='link',
                          processors=[],
                          format='PNG',
                          options={'quality': 60})
    thumbnail = ImageSpecField(source='link',
                               processors=[ResizeToFit(270, 270)],
                               format='PNG',
                               options={'quality': 60})
    paging = ImageSpecField(source='link',
                            processors=[ResizeToFit(147, 143)],
                            format='PNG',
                            options={'quality': 60})
    is_delete = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return "{} - {}".format(self.product.pk, self.product.title)

    class Meta:
        verbose_name = 'Изображение варианта товара'
        verbose_name_plural = 'Изображения вариантов товаров'


class Stock(models.Model):
    is_delete = models.BooleanField(default=False, blank=True)


class StockLocation(models.Model):
    is_delete = models.BooleanField(default=False, blank=True)


class ProductToCatalog(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    catalog = models.ForeignKey("Catalog", on_delete=models.SET_NULL, null=True)
    is_delete = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return "кат. {} товар #{}-{}".format(self.catalog.title,self.product.pk, self.product.title)

    class Meta:
        verbose_name = 'Товар в каталог'
        verbose_name_plural = 'Привязки товаров к каталогам'


class AttributeForProduct(models.Model):
    title = models.CharField(max_length=300, db_index=True)
    code = models.CharField(max_length=20, db_index=True)
    CAST_CHOICES = (
        ('str', 'Строка'),
        ('int', 'Целое число'),
        ('color', 'Цвет'),
        ('float', 'Дробное число'),
    )
    cast_type = models.CharField(max_length=10, choices=CAST_CHOICES)
    is_delete = models.BooleanField(default=False, blank=True)


class ProductAttributes(models.Model):
    attribute = models.ForeignKey(AttributeForProduct, on_delete=models.DO_NOTHING, default=None, null=True,
                                  db_index=True)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, blank=True, default=None, null=True,
                                db_index=True)
    product_variant = models.ForeignKey(ProductVariant, on_delete=models.DO_NOTHING, blank=True, default=None,
                                        null=True, db_index=True)
    value = models.CharField(max_length=300, default='n/a', blank=True)
    is_delete = models.BooleanField(default=False, blank=True)


class ProductTag(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, db_index=True, null=True)
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL, db_index=True, null=True)

    class Meta:
        unique_together = ('product', 'tag')

cms/forms/form_attribute.py
from django.forms import ModelForm
from shop.models import AttributeForProduct


class FormAttribute(ModelForm):
    class Meta:
        model = AttributeForProduct
        fields = ['title', 'code', 'cast_type']

cms/forms/form_catalog.py
from django.forms import ModelForm
from shop.models import Catalog


class FormCatalog(ModelForm):
    class Meta:
        model = Catalog
        fields = ['title', 'parent', 'code']

cms/forms/form_product.py
from django.forms import ModelForm
from shop.models import Product


class FormProduct(ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price']

cms/forms/form_tag.py
from django.forms import ModelForm
from shop.models import Tag


class FormTag(ModelForm):
    class Meta:
        model = Tag
        fields = ['title', 'code']

cms/views.py
from django.shortcuts import render

# Create your views here.

cms/views/index.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View


class IndexView(View):
    def get(self, request):
        return render(request=request, template_name='cms/index.html', context={"is_breadcrumbs": False, "landing": True})
        # return HttpResponse("Hello, world. You're at the index.")

templates/cms/products/add.html
{% extends 'cms/base.html' %}
{% load static from staticfiles %}
{% block content %}
    {% include 'cms/products/tool.html' %}

    <div class="table-responsive">
        <form method="post" id="productForm">
            {% csrf_token %}
            <div class="form-group">
                <label for="titleField">Название</label>
                <input type="text" class="form-control" id="titleField" name="title" required>
                <div class="invalid-feedback" id="feed_title"></div>
            </div>
            <div class="form-group">
                <label for="codeField">Артикул</label>
                <input type="text" class="form-control" id="codeField" name="code" required>
                <div class="invalid-feedback" id="feed_code"></div>
            </div>
            <div class="form-group">
                <label for="productTypeField">Бренд товара</label>
                <select class="form-control" id="productBrandField" name="product_brand" required>
                    <option value="" hidden>--------</option>
                    {% for pbrand in product_brand_list %}
                        <option value="{{ pbrand.pk }}">{{ pbrand.title }}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback" id="feed_product_brand"></div>
            </div>
            <div class="form-group">
                <label for="catalogField">Каталог</label>
                <select class="form-control" id="catalogField" name="catalog" required>
                    <option value="" hidden>--------</option>
                    {% for element in catalogs %}
                        <option value="{{ element.pk }}">{{ element }}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback" id="feed_catalog"></div>
            </div>
            <div class="form-group">
                <label for="productTypeField">Вид товара</label>
                <select class="form-control" id="productTypeField" name="product_class" required>
                    <option value="" hidden>--------</option>
                    {% for pclass in product_class_list %}
                        <option value="{{ pclass.pk }}">{{ pclass.title }}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback" id="feed_product_class"></div>
            </div>
            <div class="form-group">
                <label for="descriptionField">Описание</label>
                <textarea class="form-control" id="descriptionField" rows="3" name="description"></textarea>
                <div class="invalid-feedback" id="feed_description"></div>
            </div>
            <div class="form-group">
                <label for="titlePrice">Цена</label>
                <input type="number" class="form-control" id="titlePrice" name="price" required>
                <div class="invalid-feedback" id="feed_price"></div>
            </div>
            <fieldset class="form-group">
                <a href="javascript:void(0)" onclick="$('#pro-image').click()">Загрузить изображения</a>
                <input type="file" id="pro-image" name="images" style="display: none;" class="form-control" multiple>
            </fieldset>
            <div class="preview-images-zone">

            </div>
            <div class="form-group">
                <button type="button" id="submit" onclick="submitProduct()">СОХРАНИТЬ</button>
            </div>
        </form>
    </div>

    <script>
        function submitProduct() {
            var data_items = new FormData($('#productForm')[0]);
            $.ajax({
                type: 'POST',
                url: '{% url 'cms.product.add' %}',
                beforeSend: function () {
                },
                data: data_items,
                processData: false,
                contentType: false,
                dataType: 'json',
                statusCode: {
                    400: function (msg) {
                        msg = msg.responseJSON;
                        if(msg.errors){
                            $.each(msg.errors, function (key, value) {
                               $('[name="'+key+'"]').addClass('is-invalid');
                               $('#feed_'+key).text(value);
                            });
                        }
                    },
                    202: function (msg) {
                        console.debug(msg);
                    },
                    200: function (msg) {
                        console.debug(msg);
                    },
                    500: function (msg) {
                        console.debug(msg);
                    }
                }
            });
        }
    </script>
{% endblock %}

templates/cms/products/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cms/products/edit.html
{% extends 'cms/base.html' %}
{% load static from staticfiles %}
{% block content %}
    <div class="table-responsive">
        <form method="post" id="productForm">
            {% csrf_token %}
            <div class="form-group col-md-12">
                <label for="titleField">Название</label>
                <input type="text" class="form-control" id="titleField" name="title" required
                       value="{{ product.title }}">
                <div class="invalid-feedback" id="feed_title"></div>
            </div>
            <div class="form-group col-md-4">
                <label for="codeField">Артикул</label>
                <input type="text" class="form-control input-sm" id="codeField" name="code" required value="{{ product.code }}">
                <div class="invalid-feedback" id="feed_code"></div>
            </div>
            <div class="form-group col-md-4">
                <label for="productTypeField">Бренд товара</label>
                <select class="form-control" id="productBrandField" name="product_brand" required>
                    <option value="" hidden>--------</option>
                    {% for pbrand in product_brand_list %}
                        <option value="{{ pbrand.pk }}"
                                {% if product.brand.pk == pbrand.pk %}selected{% endif %}>{{ pbrand.title }}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback" id="feed_product_brand"></div>
            </div>
            <div class="form-group col-md-4">
                <label for="catalogField">Каталог</label>
                <select class="form-control" id="catalogField" name="catalog" required>
                    <option value="" hidden>--------</option>
                    {% for element in catalogs %}
                        <option value="{{ element.pk }}"
                                {% if catalog == element.pk %}selected{% endif %}>{{ element }}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback" id="feed_catalog"></div>
            </div>
            <div class="form-group col-md-4">
                <label for="productTypeField">Вид товара</label>
                <select class="form-control" id="productTypeField" name="product_class" required>
                    <option value="" hidden>--------</option>
                    {% for pclass in product_class_list %}
                        <option value="{{ pclass.pk }}"
                                {% if product.product_class.pk == pclass.pk %}selected{% endif %}>{{ pclass.title }}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback" id="feed_product_class"></div>
            </div>
            <div class="form-group col-md-4">
                <label for="titlePrice">Цена</label>
                <input type="text" class="form-control" id="titlePrice" name="price" required
                       value="{{ product.price|floatformat:2  }}">
                <div class="invalid-feedback" id="feed_price"></div>
            </div>
            <div class="form-group col-md-12">
                <label for="descriptionField">Описание</label>
                <textarea class="form-control" id="descriptionField" rows="3"
                          name="description">{{ product.description }}</textarea>
                <div class="invalid-feedback" id="feed_description"></div>
            </div>
            <div class="form-group">
                <div>
                    <ul class="ace-thumbnails clearfix">
                        {% for image in product.productimage_set.all %}
                            <li>
                                <a href="{{ image.x600.url }}" data-rel="colorbox">
                                    <img width="220" height="220" alt="220x220" src="{{ image.thumbnail.url }}"/>
                                </a>
                                <div class="tools">
                                    <a href="{{ image.full.url }}" target="_blank">
                                        <i class="ace-icon fa fa-link"></i>
                                    </a>
                                    <a href="#">
                                        <i class="ace-icon fa fa-times red"></i>
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="form-group">
                <div id="dropzone" class="dropzone well dz-clickable"></div>
            </div>
            <div class="form-group">
                <div class="fallback">
                    <input name="images" type="file" multiple/>
                </div>
            </div>
            <div id="preview-template" class="hide">
                <div class="dz-preview dz-file-preview">
                    <div class="dz-image">
                        <img data-dz-thumbnail=""/>
                    </div>

                    <div class="dz-details">
                        <div class="dz-size">
                            <span data-dz-size=""></span>
                        </div>

                        <div class="dz-filename">
                            <span data-dz-name=""></span>
                        </div>
                    </div>

                    <div class="dz-progress">
                        <span class="dz-upload" data-dz-uploadprogress=""></span>
                    </div>

                    <div class="dz-error-message">
                        <span data-dz-errormessage=""></span>
                    </div>

                    <div class="dz-success-mark">
											<span class="fa-stack fa-lg bigger-150">
												<i class="fa fa-circle fa-stack-2x white"></i>

												<i class="fa fa-check fa-stack-1x fa-inverse green"></i>
											</span>
                    </div>

                    <div class="dz-error-mark">
											<span class="fa-stack fa-lg bigger-150">
												<i class="fa fa-circle fa-stack-2x white"></i>

												<i class="fa fa-remove fa-stack-1x fa-inverse red"></i>
											</span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="button" id="submit" onclick="submitProduct()">СОХРАНИТЬ</button>
            </div>
        </form>
    </div>

    <script>
        function submitProduct() {
            var data_items = new FormData($('#productForm')[0]);
            data_items.delete('images');
            if (window.File && window.FileList && window.FileReader) {
                {
                    try {
                        var files = myDropzone.getAcceptedFiles();
                        $.each(files, function (index, value) {
                            data_items.append('images', value);
                        });
                    } catch (e) {

                    }
                }
            }
            $.ajax({
                type: 'POST',
                url: '{% if product.pk %}{% url 'cms.product.edit' product_id=product.pk %}{% else %}{% url 'cms.product.add' %}{% endif %}',
                beforeSend: function () {
                    bootbox.dialog({
                    title: "Process...",
                    message: '<p><i class="fa fa-spin fa-spinner"></i> Loading...</p>'
                    });
                },
                data: data_items,
                processData: false,
                contentType: false,
                dataType: 'json',
                statusCode: {
                    400: function (msg) {
                        msg = msg.responseJSON;
                        if (msg.errors) {
                            $.each(msg.errors, function (key, value) {
                                $('[name="' + key + '"]').addClass('is-invalid');
                                $('#feed_' + key).text(value);
                            });
                        }
                    },
                    202: function (msg) {
                        console.debug(msg);
                    },
                    200: function (msg) {
                        {% if product.pk %} window.location.reload(){% else %}window.location = '{% url 'cms.product.list' %}'{% endif %};
                    },
                    500: function (msg) {
                        console.debug(msg);
                    }
                }
            });
        }
    </script>
    <link rel="stylesheet" href="{% static "cms/assets/css/dropzone.min.css" %}"/>
{% endblock %}
{% block exta_files %}
    <link rel="stylesheet" href="{% static "cms/assets/css/colorbox.min.css" %}"/>
    <script src="{% static "cms/assets/js/dropzone.min.js" %}"></script>
    <script src="{% static "cms/assets/js/jquery.colorbox.min.js" %}"></script>
    <script type="text/javascript" src="{% static "cms/assets/js/bootbox.js" %}"></script>
    <script type="text/javascript" src="{% static "cms/js/product.js" %}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" type="text/css" media="all" rel="stylesheet" />

    <link href="{%  static "froala_editor/css/froala_editor.min.css" %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{%  static "froala_editor/css/froala_style.min.css" %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{%  static "froala_editor/css/plugins/colors.min.css" %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{%  static "froala_editor/css/plugins/line_breaker.min.css" %}" type="text/css" media="all" rel="stylesheet" />

    <script type="text/javascript" src="{%  static "froala_editor/js/froala_editor.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/colors.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/align.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/font_size.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/line_breaker.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/lists.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/paragraph_format.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/paragraph_style.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/table.min.js" %}"></script>
    <script type="text/javascript" src="{%  static "froala_editor/js/plugins/word_paste.min.js" %}"></script>
    <script> $(function() { $('#descriptionField').froalaEditor() }); </script>
{% endblock %}

templates/cms/products/list-item-1.html
<tr>
    <td class="center">
        <label class="pos-rel">
            <input type="checkbox" class="ace mass-product" value="{{ product.pk }}"/>
            <span class="lbl"></span>
        </label>
    </td>

    <td class="center">
        <div class="action-buttons">
            <a href="#" class="green bigger-140 show-details-btn" title="Показать детали">
                <i class="ace-icon fa fa-angle-double-down"></i>
                <span class="sr-only">Детали</span>
            </a>
        </div>
    </td>

    <td>
        <a href="{% url 'cms.product.edit' product_id=product.pk %}">{{ product.title }}</a>
    </td>
    <td>{{ product.price|floatformat:2 }}</td>
    <td class="hidden-480">0</td>
    <td>{{ product.created_at }}</td>

    <td class="hidden-480">
        {% if product.is_featured %} <span class="label label-sm label-success">Доступен</span> {% else %}
            <span class="label label-sm label-warning">Не доступен</span> {% endif %}
    </td>

    <td>
        <div class="hidden-sm hidden-xs btn-group">
            {% if product.is_featured %}
                <button class="btn btn-xs btn-warning" title="пометить как недоступен">
                    <i class="ace-icon fa fa-check bigger-120"></i>
                </button>
            {% else %}
                <button class="btn btn-xs btn-success" title="пометить как доступен">
                    <i class="ace-icon fa fa-check bigger-120"></i>
                </button>
            {% endif %}
            <a href="{% url 'cms.product.edit' product_id=product.pk%}" class="btn btn-xs btn-info" title="изменить">
                <i class="ace-icon fa fa-pencil bigger-120"></i>
            </a>
            <button data-id="{{ product.pk }}" class="btn btn-xs btn-info copy-product" title="добавить копированием">
                <i class="ace-icon fa fa-copy bigger-120"></i>
            </button>

            <button class="btn btn-xs btn-danger" title="удалить">
                <i class="ace-icon fa fa-trash-o bigger-120"></i>
            </button>
        </div>
    </td>
</tr>
<tr class="detail-row">
    <td colspan="8">
        <div class="table-detail">
            <div class="row">
                <div class="col-xs-12 col-md-4">
                    <div id="carousel-{{ product.pk }}" class="carousel slide" data-ride="carousel">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            {% for img in product.productimage_set.all %}
                                <div class="item {% if forloop.first %}active{% endif %}">
                                <img src="{{ img.thumbnail.url }}" alt="...">
                            </div>
                            {% endfor %}
                        </div>
                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-{{ product.pk }}" role="button"
                           data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-{{ product.pk }}" role="button"
                           data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>

                <div class="col-xs-12 col-md-8">
                    <p>{{ product.description }}</p>
                </div>
            </div>
        </div>
    </td>
</tr>

templates/cms/products/list-item.html
<tr>
    <td><a href="{% url 'cms.product.edit' product_id=product.pk %}">EDIT</a>
        <input type="checkbox" name="product[]" value="{{ product.pk }}"/></td>
    <td>{{ product.pk }}</td>
    <td>{{ product.title }}</td>
    <td>{% for cat in  product.producttocatalog_set.all %}{{ cat.catalog }}, {% endfor %}</td>
    <td>
        <div id="carousel{{ product.pk }}" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {% for img in product.productimage_set.all %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img class="d-block w-100" src="{{ img.thumbnail.url }}" alt="">
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carousel{{ product.pk }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel{{ product.pk }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </td>
    <td>{{ product.price }}</td>
    <td> 1</td>
</tr>